### ISSUE TITLE
Notice: Undefined index: QUERY_STRING

### ISSUE THREAD

**Issue by eriknyk** [jaytaph/HTRouter#1]
Hi, what do you think about this error.

Regards.

Notice: Undefined index: QUERY_STRING in /Users/erik/Downloads/jaytaph-HTRouter-8c50727/htrouter/HTRouter.php on line 455
Hello world!

Array
(
    [DOCUMENT_ROOT] => /Users/erik/Downloads/jaytaph-HTRouter-8c50727/public
    [REMOTE_ADDR] => 127.0.0.1
    [REMOTE_PORT] => 50748
    [SERVER_SOFTWARE] => PHP 5.4.0 Development Server
    [SERVER_PROTOCOL] => HTTP/1.1
    [SERVER_NAME] => 0.0.0.0
    [SERVER_PORT] => 8081
    [REQUEST_URI] => /index.php
    [REQUEST_METHOD] => GET
    [SCRIPT_NAME] => /index.php
    [SCRIPT_FILENAME] => /Users/erik/Downloads/jaytaph-HTRouter-8c50727/public/index.php
    [PHP_SELF] => /index.php
    [HTTP_HOST] => 127.0.0.1:8081
    [HTTP_CONNECTION] => keep-alive
    [HTTP_USER_AGENT] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.83 Safari/535.11
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    [HTTP_ACCEPT_ENCODING] => gzip,deflate,sdch
    [HTTP_ACCEPT_LANGUAGE] => es-ES,es;q=0.8
    [HTTP_ACCEPT_CHARSET] => ISO-8859-1,utf-8;q=0.7,*;q=0.3
    [REQUEST_TIME_FLOAT] => 1332474199.7032
    [REQUEST_TIME] => 1332474199
    [PATH_INFO] => 
    [QUERY_STRING] => 
)

**Comment by webdevilopers** [comment]
Same here - issue open since 2012? Please help, @jaytaph ! Thanks

**Comment by jaytaph** [comment]
I've added this to the code in PR #8
